"""initial

Revision ID: c86e6132a2fd
Revises: 
Create Date: 2026-07-14 11:57:28.817616

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c86e6132a2fd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_knowledge_classification_log_content_attempt', 'knowledge_classification_log', ['source_type', 'source_id', 'canonical_content_hash', 'prompt_version', 'attempt_no'])
    op.create_index(op.f('ix_knowledge_classification_state_next_retry_at'), 'knowledge_classification_state', ['next_retry_at'], unique=False)
    op.alter_column('knowledge_documents', 'index_attempts',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_knowledge_documents_next_index_retry_at'), 'knowledge_documents', ['next_index_retry_at'], unique=False)
    op.alter_column('market_evidence', 'trade_date',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    op.alter_column('market_evidence', 'brief_type',
               existing_type=sa.VARCHAR(length=16),
               nullable=False)
    op.alter_column('market_evidence', 'source',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('market_evidence', 'source_url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('market_evidence', 'reliability',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('market_evidence', 'fetched_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.drop_index(op.f('ix_market_evidence_raw_hash'), table_name='market_evidence')
    op.drop_constraint(op.f('uq_market_evidence_hash'), 'market_evidence', type_='unique')
    op.create_index(op.f('ix_market_evidence_brief_type'), 'market_evidence', ['brief_type'], unique=False)
    op.create_unique_constraint('uq_evidence_trade_brief_url', 'market_evidence', ['trade_date', 'brief_type', 'source_url'])
    op.drop_column('market_evidence', 'tags_json')
    op.drop_column('market_evidence', 'collected_at')
    op.drop_column('market_evidence', 'raw_excerpt')
    op.drop_column('market_evidence', 'related_themes_json')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('market_evidence', sa.Column('related_themes_json', sa.VARCHAR(), nullable=True))
    op.add_column('market_evidence', sa.Column('raw_excerpt', sa.VARCHAR(), nullable=True))
    op.add_column('market_evidence', sa.Column('collected_at', sa.VARCHAR(), nullable=True))
    op.add_column('market_evidence', sa.Column('tags_json', sa.VARCHAR(), nullable=True))
    op.drop_constraint('uq_evidence_trade_brief_url', 'market_evidence', type_='unique')
    op.drop_index(op.f('ix_market_evidence_brief_type'), table_name='market_evidence')
    op.create_unique_constraint(op.f('uq_market_evidence_hash'), 'market_evidence', ['raw_hash'])
    op.create_index(op.f('ix_market_evidence_raw_hash'), 'market_evidence', ['raw_hash'], unique=False)
    op.alter_column('market_evidence', 'fetched_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('market_evidence', 'reliability',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('market_evidence', 'source_url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('market_evidence', 'source',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('market_evidence', 'brief_type',
               existing_type=sa.VARCHAR(length=16),
               nullable=True)
    op.alter_column('market_evidence', 'trade_date',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    op.drop_index(op.f('ix_knowledge_documents_next_index_retry_at'), table_name='knowledge_documents')
    op.alter_column('knowledge_documents', 'index_attempts',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_knowledge_classification_state_next_retry_at'), table_name='knowledge_classification_state')
    op.drop_constraint('uq_knowledge_classification_log_content_attempt', 'knowledge_classification_log', type_='unique')
    # ### end Alembic commands ###
